### ISSUE TITLE
Can't select audio outputs in sidebar

### ISSUE THREAD

**Issue by thumos333** [budgie-desktop/budgie-desktop#1026]
Solus 2017.04.18.0 64-bit
Budgie version: 10.3.1-131
There's a built-in soundcard and an external USB Dock audio on my Thinkpad T440s. Budgie has recently had problem displaying these audio options in the sidebar. They still work but I can't choose between them. Please see the screenshot below.
![screenshot from 2017-07-12 10-28-42](https://user-images.githubusercontent.com/29035180/28109226-fca6f2c8-66f6-11e7-856d-63e32cf02771.png)

**Comment by ikeydoherty** [comment]
Fixed in git, will be in the next release (Also a dupe :))

**Comment by thumos333** [comment]
In the latest Budgie, 10.4, this issue is still there. Here's a screenshot. It's only possible to select input / output sources in Sound in the Settings panel.

![screenshot from 2018-01-30 09-04-50](https://user-images.githubusercontent.com/29035180/35550767-f998f38e-059c-11e8-8ceb-93cd26cd20bd.png)

![screenshot from 2018-01-30 09-12-11](https://user-images.githubusercontent.com/29035180/35550916-b17c68b4-059d-11e8-8d73-fe8a9bab9294.png)
