### ISSUE TITLE
Order of top panel applets in Budgie Settings

### ISSUE THREAD

**Issue by rossorp** [budgie-desktop/budgie-desktop#1058]
**Operating System**: Solus
**Budgie version**: v10.3.1-404-g128a50a

When I switched my computer on this morning, I found all the applets on the top panel has disappeared. I went to budgie settings to set it up again and found some issues with the ordering of the applets, specifically at the bottom of the list (for the very right of the panel). 

![screenshot from 2017-07-21 07-04-13](https://user-images.githubusercontent.com/1185919/28451413-083c14ac-6de5-11e7-96f3-4a1da8dde80f.png)

In this screenshot, the list of applets indicates that the order (left-to-right) is Night Light - Raven Sidebar Control - Clock, however if you look to the top-right of the screenshot, the order is actually Night Light - Clock - Raven Sidebar Control. This happened after I added the sidebar control applet and moved it down the list to place it on the far right. In the settings window it stops at the second-to-last spot, even though it changes in the panel itself.

To reproduce:
1. Add applet to the top panel in Budgie Settings.
2. Click the down arrow to move it down the list to the bottom.

Also, when confirming the bug, I noticed that the down arrow is disabled for the last item in the applet list (makes sense as it can't be moved down further as it is the last one already), but it is also disabled for the second last one as well (refer screenshot below). As this can in theory be moved down the list to place the applet at the far right of the panel, the down arrow should be enabled.

![image](https://user-images.githubusercontent.com/1185919/28451663-74902534-6de6-11e7-9ce3-61f4d5e0e08f.png)

**Comment by ikeydoherty** [comment]
Cannot confirm, please make sure you've rebooted since applying the latest updates, because I'm pretty darn sure I fixed this already in git

**Comment by rossorp** [comment]
I installed updates, and have since rebooted twice before reporting the bug. I have just rebooted again to make sure and still have the same issues.

Upon reboot just now I:
1. Entered my password to unlock password store.
2. Opened the Raven Sidebar Control and opened the settings window from there.
3. Went to the Top Panel section, and took this screenshot:

![image](https://user-images.githubusercontent.com/1185919/28452080-ddb24996-6de8-11e7-9a6c-581cfd274ccc.png)

Without changing anything, the order of the applets in the settings window does not match with top panel (last five items are out of order).

**Comment by ikeydoherty** [comment]
Is the panel itself using the correct layout?

**Comment by rossorp** [comment]
Apart from the issue with the last two items, I would say the settings window shows the "correct" order. I can get the top panel to actually reflect the same order, the order that I want, by reordering in settings by using the up arrow only. However, the order in the top panel seems to change randomly if I add another applet and move it down the list.

1. Starting order (order the same in settings and top panel)
![image](https://user-images.githubusercontent.com/1185919/28452649-92f198aa-6deb-11e7-85e8-353e1ccdf193.png)

2. Add spacer (no change, spacer auto-added to centre section, orders still match):
![image](https://user-images.githubusercontent.com/1185919/28452696-cc014280-6deb-11e7-9f65-2f81d34e2620.png)

3. Press down button to move spacer from Centre to Right section:
![image](https://user-images.githubusercontent.com/1185919/28452744-06a868aa-6dec-11e7-97ef-5c919868b6ca.png)
Note that with this one action, the order of the last two items in the top panel has swapped, while their order in settings has stayed the same (in the correct order I suppose as it was the starting order).

**Comment by ikeydoherty** [comment]
OK so its possible then at some time a bug broke the internal layout of those applets within the settings.

The only thing I can recommend at the moment is doing a full panel reset and then re-doing your layout, and seeing if the problem persists after that?

`nohup budgie-panel --reset --replace&`

**Comment by rossorp** [comment]
Right, that seems to have done the trick. Running that command appears to have cleared up all those problems I was having. Will make a note of that just in case for the future.

Cheers for the help.

**Comment by Coeur-Noir** [comment]
Still happens in Ubuntu-Budgie 18.04 but will try the
`nohup budgie-panel --reset --replace&`
( for reference https://forum.ubuntu-fr.org/viewtopic.php?id=2026964 )

**Comment by Silcore** [comment]
This issue persists in Ubuntu-Budgie 18.04, with Budgie 10.4. After resetting the layout with `nohup budgie-panel --reset --replace&`, moving to the Budgie Desktop Settings application and attempting to move _Raven Sidebar Control_ up on the applet list prevents that same applet from being moved back down. After configuring the Budgie panel to my liking, adjusting spacing and moving applets on the furthest right side of the bar is nightmarish. Applets do not retain their position through restart, although this seems to only be affecting the **furthest right** applets on the bar (and furthest down in the applet configuration menu).

By looking at the manner the configuration menu behaves, it seems as though the applets are assumed to be at the furthest right position (thus disabling the down-shift button) when they are actually not.
