### ISSUE TITLE
Some of the tray icons in top the right get stacked

### ISSUE THREAD

**Issue by Louis-Simon22** [budgie-desktop/budgie-desktop#1296]
**Operating System**: e.g. Solus 3
**Budgie version**: Budgie 10.4

**The issue encountered**
Some of the tray icons in top the right stack on top of one another

**Steps to reproduce the issue**
It started after I added the keyboard layout indicator as a widget in the right section of my top panel.
Here is a screenshot : 
![capture du 2018-01-23 16-22-42](https://user-images.githubusercontent.com/22861550/35303844-6a44dc06-0061-11e8-84fd-fb4312335c95.png)
The icons that are supposed to be there are : 
keyboard layout indicator, discord, wifi, notifications, battery, sound and power.

**Comment by Kyrio** [comment]
i have the same issue, the network icons (Wi-Fi and wired, I presume) are stacked in the system tray. Removing the system tray and adding it again in the Budgie Settings app fixes it, but the issue comes back if I reboot Solus.

![image](https://user-images.githubusercontent.com/3719464/35653038-9056566e-06e6-11e8-8ceb-ccf7a61c2af1.png)

**Comment by subrms** [comment]
You can put the panel down and  re put it on top to make disapear the issue; I had the same problem but after update was fixed.

**Comment by endorfina** [comment]
@subrms Are you on some unstable build? It's still here.
![screenshot from 2018-02-16 09-35-43](https://user-images.githubusercontent.com/35767873/36299581-f52d74d2-12fd-11e8-87d5-a965edd099a6.png)

**Comment by Raqbit** [comment]
Same issue here, is happening quite randomly at boot. @subrms's suggestion made it go away, although now there are boxes around some of the icons (Doesn't match up with the default dark theme)

**Comment by s-oehding** [comment]
Same Issue here, Icons are stacked, Network Icon sometimes appear twice and I got black boxes around Icons.

![stray](https://user-images.githubusercontent.com/8821978/38545653-d510d3d4-3caa-11e8-91d8-615eca4301ce.png)

**Comment by fossfreedom** [comment]
Hopefully fixed with this commit - please try it - https://github.com/budgie-desktop/budgie-desktop/commit/a818a550cd8e81d01865dcad72161518cc09756c

**Comment by s-oehding** [comment]
Yep, seems to be fixed now :) Thx!

**Comment by SpinAttack** [comment]
I'm on Manjaro with Budgie and I still have this issue. Is this a Manjaro only problem now?

**Comment by thumos333** [comment]
I still have this issue on the latest Solus.

![Screenshot from 2019-08-22 12:27:15](https://user-images.githubusercontent.com/29035180/63503509-46201b00-c4d8-11e9-9696-fd73d0d5dfd3.png)

**Comment by AlienTux** [comment]
I have the same problem, but I found out that if I move the panel from top to bottom or bottom to top it gets fixed. I do this almost every time I log into Solus and it has always worked. I know it's not a fix, but it might help someone.

**Comment by thumos333** [comment]
AlienTux's trick has worked for me.

Two more characteristics of this bug:

* It only appears on my computer with non-HD 5:4 screen. It does not appear on a full HD screen computer.
* If I move the system tray applet icon from the right section to the center or left section of the bottom panel, the problem with the icon worsens: either more instances of it appear, or it becomes empty space.

**Comment by AlienTux** [comment]
Glad it worked for you!

I do have to say, however, that the bug happens in my Laptop with a 1920x1080p screen :( I don't think it's resolution related.

**Comment by thumos333** [comment]
Alien Tux, this is curious, given that I have the same set of icons on both my machines. On the full HD one, the issue never appears though.

**Comment by JoshStrobl** [comment]
Duplicate of #1249

**Comment by ktw** [comment]
Sill a problem in the new 10.5.1-204

**Comment by JoshStrobl** [comment]
I closed this as a duplicate, check the task that is clearly still open...
