### ISSUE TITLE
When DBusActivatable (with some applicaitons) is set to "true", you can't run them from budgie-run-dialog

### ISSUE THREAD

**Issue by JannikHa** [budgie-desktop/budgie-desktop#658]
**Operating System**: Solus 1.2.0.5 + Arch Linux
**Budgie version**: Budgie 10.2.7

When answering some support tickets, I [discovered a problem regarding **budgie-run-dialog**](https://github.com/solus-project/budgie-desktop/issues/599#issuecomment-254506478).

The problem is basically as described in the following:

A program like **gedit** or **corebird** have "DBusActivatable" set to true in their /usr/share/applications/ entry. If it's set to true, you can either **not**, or **sometimes** start it with **budgie-run-dialog**, but only if you try to open it multiple times in a row. When DBusActivatable is set to "false" or compeltely removed, it starts normally. It's a really weird behaviour...

Here is a video I made to demonstrate the problem. Sorry for the flickering and such...:

http://sendvid.com/qvxnywhi

**Comment by ikeydoherty** [comment]
Buh.

**Comment by ikeydoherty** [comment]
So I thought I fixed this. Basically when dbus activatable is *true* the API just completely lies about when it is and isn't launched, so then we quit before the message gets across dbus...

**Comment by JannikHa** [comment]
It's just **really, really weird.** When dbus activatable is *true* and i open, for example **gedit**, 2 fast times in a row, **it opens**. But just after the second try when there wasn't much time (let's say about 5 Seconds) in between those 2 tries. It's really not a huge deal IMO, just really strange, especially because it just applies to specific types of applications.

**Comment by streambinder** [comment]
Actually, it's still happening (tested with _gedit_ and many more apps).

**Comment by ikeydoherty** [comment]
^ Implemented, fixed, closed.

**Comment by m-delvalle** [comment]
@ikeydoherty after updating (including some budgie-related packages) I'm still having this issue :cry: 
Is this fix in the "stable" repo? Should this already be fixed on my install? Or do I have to wait until this particular fix gets published to end users?

**Comment by ikeydoherty** [comment]
Needs releasing @m-delvalle - we're planning a 10.2.9 release. It's not really backportable I'm afraid, hence needing a new release

**Comment by m-delvalle** [comment]
@ikeydoherty np, just checking :)

**Comment by m-delvalle** [comment]
Update: just applied latest patches and it's working great now! thanks @ikeydoherty

**Comment by ikeydoherty** [comment]
Woot! :D
