### ISSUE TITLE
MPRIS applet cover is jumping depending on proportions of the actual cover image

### ISSUE THREAD

**Issue by nazar-pc** [budgie-desktop/budgie-desktop#756]
**Operating System**: Ubuntu 17.04
**Budgie version**: Budgie 10.2.9

**The issue encountered**
When switching tracks in MPRIS applet with its prev/next buttons, buttons position might jump up and down as size of cover image of the track being played changes.

It would be more convenient to see the behavior when fixed square area is dedicated for cover image and actual image being somehow placed inside without affecting applet size.

**Comment by JoshStrobl** [comment]
Should be resolved as of https://github.com/budgie-desktop/budgie-desktop/commit/fee14735ce2c0b1e11dbc358ed23d4dc1d520025

**Comment by nazar-pc** [comment]
As of Budgie 10.4 it is not fixed. Cover image always 100% width, but height and thus media controls still change all the time.
