### ISSUE TITLE
popovers appear from the top

### ISSUE THREAD

**Issue by Solarunit** [budgie-desktop/budgie-desktop#867]
**Operating System**: Snapshot 2017.04.18.0 
**Budgie version**: 10.3.1 (?)

> Budgie 10.3 features numerous fixes for GTK 3.22. For starters, Budgie Menu and other popovers will no longer appear to move from the top to the bottom of your screen when the Budgie panel is located on the bottom. 

But I have noticed the same problem with volume popover. See gif (~10 sec) 

![Alt Text](http://i.imgur.com/Y2glZZ7.gif)

 ...

**Comment by JannikHv** [comment]
Already a known issue for a few months :P

**Comment by ikeydoherty** [comment]
It seems to be linked with animations. So if you have slow GTK FPS (which it seems you do) then the bug seems to prevail. I cannot for the life of me reproduce it on my NUC - yet I can in a VM now.

**Comment by Solarunit** [comment]
> So if you have slow GTK FPS (which it seems you do) then the bug seems to prevail.

I have a rather powerful lintel skylake cpu if its related...
-----
The same bug in VM too

**Comment by branchard** [comment]
I have the same issue with the Budgie Menu in 10.3.1.
![peek 21-04-2017 02-58](https://cloud.githubusercontent.com/assets/6990948/25258310/b5b76418-263e-11e7-9147-1a6c49181227.gif)

**Comment by JoshStrobl** [comment]
Duplicate of #292

**Comment by fossfreedom** [comment]
@JoshStrobl 292 as closed as is this one - one at least should remain open

**Comment by JoshStrobl** [comment]
@fossfreedom The issue should be resolved in 10.3/10.3.1. I don't see a reason either of them need to be opened.

**Comment by fossfreedom** [comment]
@JoshStrobl issue is reduced - its not resolved - latest report is on G+ Solus community post.

**Comment by bmeznarsic** [comment]
Can confirm. Not fixed.

**Comment by mangueLinux** [comment]
I can confirm this also happens to me. Fresh install of ubuntu budgie 17.04. I'm forced to use the bar at the top.

**Comment by ikeydoherty** [comment]
Ok - only need the one confirmation :)

**Comment by turbotum** [comment]
Who do I have to throw money at to see this fixed, this is one major ugly ruining an otherwise very nice desktop experience.

**Comment by ikeydoherty** [comment]
It will not be fully resolved until Budgie 11. As it stands right now, the use of GtkPopover is the only reason this is happening. Less GTK = less janky bugs like this one.

**Comment by marcoms** [comment]
@ikeydoherty I suppose its best to wait until the rewrite before we open issues with stuff like animations etc.? I have a few in my mind but I'm not sure if I should report them.

**Comment by ikeydoherty** [comment]
How dya mean? If its relating to the popovers then the popover animation is down to GTK

**Comment by ikeydoherty** [comment]
Now fixed in git by replacing `GtkPopover` with `BudgiePopover`. Will be available in the next release

**Comment by marcoms** [comment]
@ikeydoherty It was stuff like flickering jumpy animations with popovers, but as you say its probably a GTK issue.

**Comment by ikeydoherty** [comment]
Yeah we had roughly 10 or so issues open for this

**Comment by lupodellasleppa** [comment]
Still having on freshly installed Debian Stretch

**Comment by fossfreedom** [comment]
This will be fixed when you upgrade to Buster.
